# -*- coding: utf-8 -*-
"""2203A51583

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qFTwUCJLm9V8NyWc_YlfaK-FSvlQfVdX
"""

import numpy as np

import numpy as py

list=[1,2,3,4]

print(list)

import numpy as np

import pandas as pd

list=[1,2,3,4,5]

array =np.array(list)

print(array)

import numpy as np

import pandas as pd

list=[6,7,8,9]

array=np.array(list)

print(type(array))

print(type(list))

import numpy as np

import pandas as pd

array1=np.array([1,2,3,4])

array2=np.array([6,7,8,9])

result1=np.multiply(array1,array2)

print(result1)

result2=np.divide(array1,array2)

print(result2)

result3=np.power(array1,array2)

print(result3)

import numpy as np

my_array =np.array([1,2,3])

result_sin=np.sin(my_array)

print("NumPy sin():",result_sin)

result_log=np.log(my_array)

print("\nNumPy log():",result_log)

result_log2=np.log2(my_array)

print("\nNumPy log2():",result_log2)

result_exp=np.exp(my_array)

print("\nNumPy exp():",result_exp)

import matplotlib.pyplot as plt

people=['Kiran','Arjun','Vijay','Varun']

age=[25,30,35,40]

height=[145,151,165,173]

weight=[45,55,65,75]

plt.figure(figsize=(5,5))

plt.scatter(age,height,s=weight,c='blue',alpha=0.7,label='weight')

plt.title('Scatter Plot of Age vs Height with Weight')

plt.xlabel('Age')

plt.ylabel('Height')

plt.legend()

plt.grid(True)

plt.show()

plt.figure(figsize=(8, 6))

bar_width = 0.3

index = range(len(people))

plt.bar(index,weight,bar_width,color='green',label='weight')

plt.title('Bar Chart of weight for Each Person')

plt.xlabel('People')

plt.ylabel('Weight')

plt.xticks(index,people)

plt.legend()

plt.show()

plt.figure(figsize=(8, 6))

plt.hist(age, bins=5, color='orange', edgecolor='black')

plt.title('Histogram of Age Distribution')

plt.xlabel('Age')

plt.ylabel('Frequency')

plt.grid(axis='y', alpha=0.75)

plt.show()

